#!/usr/bin/env bash
#
# delete all personal posts and pages

echo 'delete all personal posts and pages'

rm _posts/*

rm images/*

rm apps.html favicon.ico google*.html links.html national-parks.html search.html

echo 'done!'
